# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cameracontrols.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(662, 795)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_capture = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_capture.setEnabled(False)
        self.pushButton_capture.setGeometry(QtCore.QRect(450, 650, 101, 91))
        self.pushButton_capture.setSizeIncrement(QtCore.QSize(0, 0))
        self.pushButton_capture.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Piboto Light")
        self.pushButton_capture.setFont(font)
        self.pushButton_capture.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_capture.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_capture.setAutoFillBackground(False)
        self.pushButton_capture.setStyleSheet("")
        self.pushButton_capture.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Icons/camera_on.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap("Icons/camera_off.png"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        self.pushButton_capture.setIcon(icon)
        self.pushButton_capture.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_capture.setAutoDefault(False)
        self.pushButton_capture.setDefault(False)
        self.pushButton_capture.setFlat(True)
        self.pushButton_capture.setObjectName("pushButton_capture")
        self.label_foodload = QtWidgets.QLabel(self.centralwidget)
        self.label_foodload.setEnabled(False)
        self.label_foodload.setGeometry(QtCore.QRect(30, 150, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Piboto Light")
        self.label_foodload.setFont(font)
        self.label_foodload.setObjectName("label_foodload")
        self.pushButton_camerastatus = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_camerastatus.setEnabled(True)
        self.pushButton_camerastatus.setGeometry(QtCore.QRect(420, 150, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Piboto Light")
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_camerastatus.setFont(font)
        self.pushButton_camerastatus.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_camerastatus.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_camerastatus.setAutoFillBackground(False)
        self.pushButton_camerastatus.setStyleSheet("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Icons/cameraconnect_on.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_camerastatus.setIcon(icon1)
        self.pushButton_camerastatus.setIconSize(QtCore.QSize(50, 70))
        self.pushButton_camerastatus.setFlat(False)
        self.pushButton_camerastatus.setObjectName("pushButton_camerastatus")
        self.lineEdit_build = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_build.setEnabled(False)
        self.lineEdit_build.setGeometry(QtCore.QRect(140, 390, 261, 41))
        font = QtGui.QFont()
        font.setFamily("Piboto Light")
        self.lineEdit_build.setFont(font)
        self.lineEdit_build.setText("")
        self.lineEdit_build.setClearButtonEnabled(True)
        self.lineEdit_build.setObjectName("lineEdit_build")
        self.label_software = QtWidgets.QLabel(self.centralwidget)
        self.label_software.setEnabled(False)
        self.label_software.setGeometry(QtCore.QRect(30, 330, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Piboto Light")
        self.label_software.setFont(font)
        self.label_software.setObjectName("label_software")
        self.label_email = QtWidgets.QLabel(self.centralwidget)
        self.label_email.setEnabled(False)
        self.label_email.setGeometry(QtCore.QRect(30, 90, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Piboto Light")
        font.setPointSize(12)
        self.label_email.setFont(font)
        self.label_email.setObjectName("label_email")
        self.label_name = QtWidgets.QLabel(self.centralwidget)
        self.label_name.setEnabled(False)
        self.label_name.setGeometry(QtCore.QRect(30, 30, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Piboto Light")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_name.setFont(font)
        self.label_name.setObjectName("label_name")
        self.pushButton_liveView = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_liveView.setEnabled(False)
        self.pushButton_liveView.setGeometry(QtCore.QRect(420, 210, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Piboto Light")
        self.pushButton_liveView.setFont(font)
        self.pushButton_liveView.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Icons/liveview_on.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon2.addPixmap(QtGui.QPixmap("Icons/liveview_off.png"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        self.pushButton_liveView.setIcon(icon2)
        self.pushButton_liveView.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_liveView.setObjectName("pushButton_liveView")
        self.textEdit_camstatus = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_camstatus.setEnabled(True)
        self.textEdit_camstatus.setGeometry(QtCore.QRect(420, 320, 211, 241))
        font = QtGui.QFont()
        font.setFamily("Piboto Light")
        self.textEdit_camstatus.setFont(font)
        self.textEdit_camstatus.setAutoFillBackground(False)
        self.textEdit_camstatus.setTabChangesFocus(False)
        self.textEdit_camstatus.setReadOnly(True)
        self.textEdit_camstatus.setOverwriteMode(True)
        self.textEdit_camstatus.setObjectName("textEdit_camstatus")
        self.label_build = QtWidgets.QLabel(self.centralwidget)
        self.label_build.setEnabled(False)
        self.label_build.setGeometry(QtCore.QRect(30, 390, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Piboto Light")
        self.label_build.setFont(font)
        self.label_build.setObjectName("label_build")
        self.lineEdit_email = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_email.setEnabled(False)
        self.lineEdit_email.setGeometry(QtCore.QRect(140, 90, 491, 41))
        font = QtGui.QFont()
        font.setFamily("Piboto Light")
        self.lineEdit_email.setFont(font)
        self.lineEdit_email.setAutoFillBackground(True)
        self.lineEdit_email.setClearButtonEnabled(True)
        self.lineEdit_email.setObjectName("lineEdit_email")
        self.label_FilenameExtra = QtWidgets.QLabel(self.centralwidget)
        self.label_FilenameExtra.setEnabled(False)
        self.label_FilenameExtra.setGeometry(QtCore.QRect(30, 450, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Piboto Light")
        self.label_FilenameExtra.setFont(font)
        self.label_FilenameExtra.setObjectName("label_FilenameExtra")
        self.pushButton_quit = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_quit.setEnabled(True)
        self.pushButton_quit.setGeometry(QtCore.QRect(570, 650, 61, 91))
        font = QtGui.QFont()
        font.setFamily("Piboto Light")
        self.pushButton_quit.setFont(font)
        self.pushButton_quit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_quit.setAutoFillBackground(False)
        self.pushButton_quit.setStyleSheet("")
        self.pushButton_quit.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.pushButton_quit.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("Icons/quit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_quit.setIcon(icon3)
        self.pushButton_quit.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_quit.setFlat(True)
        self.pushButton_quit.setObjectName("pushButton_quit")
        self.textEdit_message = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_message.setEnabled(True)
        self.textEdit_message.setGeometry(QtCore.QRect(30, 510, 371, 101))
        font = QtGui.QFont()
        font.setFamily("Piboto Light")
        self.textEdit_message.setFont(font)
        self.textEdit_message.setReadOnly(True)
        self.textEdit_message.setOverwriteMode(True)
        self.textEdit_message.setObjectName("textEdit_message")
        self.label_mandatoryfields = QtWidgets.QLabel(self.centralwidget)
        self.label_mandatoryfields.setEnabled(False)
        self.label_mandatoryfields.setGeometry(QtCore.QRect(30, 690, 341, 41))
        font = QtGui.QFont()
        font.setFamily("Piboto Light")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_mandatoryfields.setFont(font)
        self.label_mandatoryfields.setAutoFillBackground(False)
        self.label_mandatoryfields.setWordWrap(False)
        self.label_mandatoryfields.setObjectName("label_mandatoryfields")
        self.lineEdit_FilenameExtra = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_FilenameExtra.setEnabled(False)
        self.lineEdit_FilenameExtra.setGeometry(QtCore.QRect(140, 450, 261, 41))
        font = QtGui.QFont()
        font.setFamily("Piboto Light")
        self.lineEdit_FilenameExtra.setFont(font)
        self.lineEdit_FilenameExtra.setText("")
        self.lineEdit_FilenameExtra.setClearButtonEnabled(True)
        self.lineEdit_FilenameExtra.setObjectName("lineEdit_FilenameExtra")
        self.comboBox_foodload = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_foodload.setEnabled(False)
        self.comboBox_foodload.setGeometry(QtCore.QRect(140, 150, 261, 41))
        font = QtGui.QFont()
        font.setFamily("Piboto Light")
        self.comboBox_foodload.setFont(font)
        self.comboBox_foodload.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.comboBox_foodload.setObjectName("comboBox_foodload")
        self.comboBox_foodload.addItem("")
        self.comboBox_foodload.addItem("")
        self.comboBox_foodload.addItem("")
        self.comboBox_foodload.addItem("")
        self.comboBox_foodload.addItem("")
        self.comboBox_foodload.addItem("")
        self.comboBox_foodload.addItem("")
        self.comboBox_foodload.addItem("")
        self.comboBox_foodload.addItem("")
        self.comboBox_foodload.addItem("")
        self.comboBox_foodload.addItem("")
        self.comboBox_foodload.addItem("")
        self.comboBox_foodload.addItem("")
        self.comboBox_foodload.addItem("")
        self.comboBox_foodload.addItem("")
        self.comboBox_foodload.addItem("")
        self.comboBox_foodload.addItem("")
        self.comboBox_foodload.addItem("")
        self.progressBar_battery = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar_battery.setEnabled(False)
        self.progressBar_battery.setGeometry(QtCore.QRect(490, 580, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Piboto Light")
        self.progressBar_battery.setFont(font)
        self.progressBar_battery.setAutoFillBackground(False)
        self.progressBar_battery.setStyleSheet("")
        self.progressBar_battery.setProperty("value", 0)
        self.progressBar_battery.setObjectName("progressBar_battery")
        self.label_other = QtWidgets.QLabel(self.centralwidget)
        self.label_other.setEnabled(False)
        self.label_other.setGeometry(QtCore.QRect(30, 210, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Piboto Light")
        self.label_other.setFont(font)
        self.label_other.setObjectName("label_other")
        self.label_copyright = QtWidgets.QLabel(self.centralwidget)
        self.label_copyright.setEnabled(False)
        self.label_copyright.setGeometry(QtCore.QRect(30, 740, 311, 21))
        font = QtGui.QFont()
        font.setFamily("Piboto Light")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_copyright.setFont(font)
        self.label_copyright.setAutoFillBackground(False)
        self.label_copyright.setWordWrap(False)
        self.label_copyright.setObjectName("label_copyright")
        self.label_sku = QtWidgets.QLabel(self.centralwidget)
        self.label_sku.setEnabled(False)
        self.label_sku.setGeometry(QtCore.QRect(30, 270, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Piboto Light")
        self.label_sku.setFont(font)
        self.label_sku.setObjectName("label_sku")
        self.lineEdit_software = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_software.setEnabled(False)
        self.lineEdit_software.setGeometry(QtCore.QRect(140, 330, 261, 41))
        font = QtGui.QFont()
        font.setFamily("Piboto Light")
        self.lineEdit_software.setFont(font)
        self.lineEdit_software.setText("")
        self.lineEdit_software.setClearButtonEnabled(True)
        self.lineEdit_software.setObjectName("lineEdit_software")
        self.label_battery = QtWidgets.QLabel(self.centralwidget)
        self.label_battery.setEnabled(False)
        self.label_battery.setGeometry(QtCore.QRect(420, 580, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Piboto Light")
        self.label_battery.setFont(font)
        self.label_battery.setObjectName("label_battery")
        self.lineEdit_name = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_name.setEnabled(False)
        self.lineEdit_name.setGeometry(QtCore.QRect(140, 30, 491, 41))
        font = QtGui.QFont()
        font.setFamily("Piboto Light")
        self.lineEdit_name.setFont(font)
        self.lineEdit_name.setClearButtonEnabled(True)
        self.lineEdit_name.setObjectName("lineEdit_name")
        self.lineEdit_sku = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_sku.setEnabled(False)
        self.lineEdit_sku.setGeometry(QtCore.QRect(140, 270, 261, 41))
        font = QtGui.QFont()
        font.setFamily("Piboto Light")
        self.lineEdit_sku.setFont(font)
        self.lineEdit_sku.setText("")
        self.lineEdit_sku.setClearButtonEnabled(True)
        self.lineEdit_sku.setObjectName("lineEdit_sku")
        self.lineEdit_other = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_other.setEnabled(False)
        self.lineEdit_other.setGeometry(QtCore.QRect(140, 210, 261, 41))
        font = QtGui.QFont()
        font.setFamily("Piboto Light")
        self.lineEdit_other.setFont(font)
        self.lineEdit_other.setClearButtonEnabled(True)
        self.lineEdit_other.setObjectName("lineEdit_other")
        self.label_quit = QtWidgets.QLabel(self.centralwidget)
        self.label_quit.setEnabled(True)
        self.label_quit.setGeometry(QtCore.QRect(570, 720, 61, 51))
        font = QtGui.QFont()
        font.setFamily("Piboto Light")
        self.label_quit.setFont(font)
        self.label_quit.setAlignment(QtCore.Qt.AlignCenter)
        self.label_quit.setObjectName("label_quit")
        self.label_capture = QtWidgets.QLabel(self.centralwidget)
        self.label_capture.setEnabled(False)
        self.label_capture.setGeometry(QtCore.QRect(470, 720, 61, 51))
        font = QtGui.QFont()
        font.setFamily("Piboto Light")
        self.label_capture.setFont(font)
        self.label_capture.setAlignment(QtCore.Qt.AlignCenter)
        self.label_capture.setObjectName("label_capture")
        self.textEdit_camstatus_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_camstatus_2.setEnabled(True)
        self.textEdit_camstatus_2.setGeometry(QtCore.QRect(420, 270, 211, 41))
        font = QtGui.QFont()
        font.setFamily("Piboto Light")
        self.textEdit_camstatus_2.setFont(font)
        self.textEdit_camstatus_2.setAutoFillBackground(False)
        self.textEdit_camstatus_2.setTabChangesFocus(False)
        self.textEdit_camstatus_2.setReadOnly(True)
        self.textEdit_camstatus_2.setOverwriteMode(True)
        self.textEdit_camstatus_2.setObjectName("textEdit_camstatus_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_foodload.setText(_translate("MainWindow", "Food load\n"
"餐饮"))
        self.pushButton_camerastatus.setText(_translate("MainWindow", "Connect to Camera\n"
"连接相机"))
        self.label_software.setText(_translate("MainWindow", "Software"))
        self.label_email.setText(_translate("MainWindow", "Email ID\n"
"电子邮件ID"))
        self.label_name.setText(_translate("MainWindow", "Name*\n"
"名称"))
        self.pushButton_liveView.setText(_translate("MainWindow", " Live View\n"
" 即时取景       "))
        self.textEdit_camstatus.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Piboto Light\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'PibotoLt\';\">Camera Summary will be shown here</span></p></body></html>"))
        self.label_build.setText(_translate("MainWindow", "Build"))
        self.lineEdit_email.setText(_translate("MainWindow", "Email1, Email2 ..."))
        self.label_FilenameExtra.setText(_translate("MainWindow", "Extra\n"
"额外的文件名"))
        self.textEdit_message.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Piboto Light\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'PibotoLt\';\">Messages will be displayed here</span></p></body></html>"))
        self.label_mandatoryfields.setText(_translate("MainWindow", "*Mandatory Fields\n"
"必须填写"))
        self.comboBox_foodload.setItemText(0, _translate("MainWindow", "Toast"))
        self.comboBox_foodload.setItemText(1, _translate("MainWindow", "Cornbread"))
        self.comboBox_foodload.setItemText(2, _translate("MainWindow", "White Cake"))
        self.comboBox_foodload.setItemText(3, _translate("MainWindow", "Cookies"))
        self.comboBox_foodload.setItemText(4, _translate("MainWindow", "Fries"))
        self.comboBox_foodload.setItemText(5, _translate("MainWindow", "Steak"))
        self.comboBox_foodload.setItemText(6, _translate("MainWindow", "Chicken"))
        self.comboBox_foodload.setItemText(7, _translate("MainWindow", "Wings"))
        self.comboBox_foodload.setItemText(8, _translate("MainWindow", "Pork Chop"))
        self.comboBox_foodload.setItemText(9, _translate("MainWindow", "Beef Stew"))
        self.comboBox_foodload.setItemText(10, _translate("MainWindow", "Cheese Melt"))
        self.comboBox_foodload.setItemText(11, _translate("MainWindow", "Yogurt"))
        self.comboBox_foodload.setItemText(12, _translate("MainWindow", "Onion"))
        self.comboBox_foodload.setItemText(13, _translate("MainWindow", "Cauliflower"))
        self.comboBox_foodload.setItemText(14, _translate("MainWindow", "Broccoli"))
        self.comboBox_foodload.setItemText(15, _translate("MainWindow", "Carrot"))
        self.comboBox_foodload.setItemText(16, _translate("MainWindow", "Cookware"))
        self.comboBox_foodload.setItemText(17, _translate("MainWindow", "Other"))
        self.label_other.setText(_translate("MainWindow", "Other*\n"
"其他"))
        self.label_copyright.setText(_translate("MainWindow", "© Ninja Test Team"))
        self.label_sku.setText(_translate("MainWindow", "SKU"))
        self.label_battery.setText(_translate("MainWindow", "Battery"))
        self.lineEdit_name.setText(_translate("MainWindow", "Your name here"))
        self.lineEdit_other.setText(_translate("MainWindow", "Other in Food load dropdown"))
        self.label_quit.setText(_translate("MainWindow", "Quit\n"
"退出"))
        self.label_capture.setText(_translate("MainWindow", "Capture\n"
"捕获"))
        self.textEdit_camstatus_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Piboto Light\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'PibotoLt\';\">Camera mode</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

